version: '3.8'

services:
  ai-hedge-fund:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://paper-api.alpaca.markets/v2/account')"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["python", "src/agents.py", "--ticker", "MSFT", "--start-date", "2024-01-01", "--end-date", "2024-03-01", "--show-reasoning"]
